server:
  port: 8080
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #jpa:
   # generate-ddl: true
    #show-sql: true
    #hibernate:
     # ddl-auto: create

   #email configuration for application.properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: tech.blog.smtp@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
