server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/natgeo
    username: root
    password: hbstudent
  #jpa:
   # generate-ddl: true
    #show-sql: true
    #hibernate:
     # ddl-auto: create

   #email configuration for application.properties

    #  spring.mail.host=smtp.gmail.com
    #  spring.mail.port=587
    #  spring.mail.username=<login user to smtp server>
    #  spring.mail.password=<login password to smtp server>
    #  spring.mail.properties.mail.smtp.auth=true
    #  spring.mail.properties.mail.smtp.starttls.enable=true
